# Generated by Django 2.1.1 on 2018-10-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181001_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Empid',
        ),
    ]
