# Generated by Django 2.1.1 on 2018-10-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_customuser_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='datesofmonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projectname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Empid', models.IntegerField(blank=True, default='')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Primarytask', models.CharField(blank=True, default='', max_length=50)),
                ('Report_date', models.DateField(null=True)),
                ('Attendence', models.CharField(default='', max_length=50)),
                ('Task', models.CharField(blank=True, choices=[('Scripting', 'Scripting'), ('Re-scripting', 'Rescripting'), ('Analysis', 'Analysis'), ('Manual', 'Manual')], max_length=50)),
                ('No_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Number of Hours')),
                ('No_count', models.IntegerField(blank=True, default=0)),
                ('Comments', models.CharField(default='', max_length=500)),
                ('dtcollected', models.DateField(auto_now_add=True)),
                ('Project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subproject_name', models.CharField(max_length=30)),
                ('Project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Project')),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='Subproject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Subproject'),
        ),
    ]
