# Generated by Django 2.1.2 on 2018-10-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20181001_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Designation',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
