# Generated by Django 2.1.2 on 2018-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='processwillInclude',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
