# Generated by Django 2.1.2 on 2018-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20181008_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Designation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
