# Generated by Django 2.1.1 on 2018-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20181008_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='Task',
            field=models.CharField(blank=True, choices=[('Scripting', 'Scripting'), ('Re-scripting', 'Rescripting'), ('Analysis', 'Analysis'), ('Manual', 'Manual'), ('Tool Monitoring', 'Tool Monitoring'), ('Meeting', 'Meeting')], max_length=50),
        ),
    ]
