# Generated by Django 2.1.1 on 2018-11-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reports',
            name='Task',
            field=models.CharField(blank=True, choices=[('Scripting', 'Scripting'), ('Re-scripting', 'Rescripting'), ('Analysis', 'Analysis'), ('Manual', 'Manual'), ('Tool Monitoring', 'Tool Monitoring'), ('Meeting', 'Meeting'), ('URL Identification', 'URL Identification'), ('Duplicate Identification', 'Duplicate Identification'), ('Hotelcode Identification', 'Hotelcode Identification')], max_length=50),
        ),
    ]
